<a href="https://colab.research.google.com/github/shannu4466/base-/blob/main/561_DAP.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
pip install numpy


In [ ]:
!pip install PyPDF2

In [ ]:
#Array creation
import numpy as np
arr=np.array([1,2,3,4,5])
print(arr)
zero_arr=np.zeros((3,3),dtype=int)
print(zero_arr) #Zero array
ones_arr=np.ones((2,2),dtype=int)
print(ones_arr) #ones array
arrange_arr=np.arange(20)
print(arrange_arr) #List of elements starts from 0 upto n-1

[1 2 3 4 5]
[[0 0 0]
 [0 0 0]
 [0 0 0]]
[[1 1]
 [1 1]]
[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


In [ ]:
#Array manupulation
reshape_arr=arr.reshape(5,1)
print(reshape_arr) #5 represents rows and 1 represnts columns

sliced_arr=arr[1:4]
print(sliced_arr)

In [ ]:
#Array Sum
arr_1=np.array([1,2,3,4,5,6])
print(arr_1+3) #Brodcasting the array

arr_2=np.array([6,7,8,9,10,11])
print(arr_1+arr_2)  #Element wise array sum

print(np.vstack(arr_1+arr_2)) #Vertically arranging the array

print(np.stack(arr_1+arr_2)) #horizontal arranging

a=np.array([[1,2,3,5],[1,2,3,4]])
print(a) #Printing 2D array
b=np.split(a,2)
print(b) #Splitting the array
c=np.transpose(a)
print(c) #Transpose of a matrix


In [ ]:
#Linear algebra with numpy
mat_1=np.array([[1,2],[3,4]])
mat_2=np.array([[4,3],[2,1]])
dot_product=np.dot(mat_1,mat_2)
print(dot_product) #Product of two matrices

#Calculating Eigen values and eigen vectors for the dot_product
Eigen_val=np.linalg.eig(dot_product)
print(Eigen_val)

In [ ]:
#Sum of 2D matrices using .sum
import numpy as np
matrix=np.array([[1,2,3],[4,5,6]])
matrix_2=np.array([[1,2,3],[4,5,6]])
print(np.sum(matrix,axis=1))
print(np.sum(matrix,axis=0))

#Mean,median,variance,sd
mat=np.array([1,2,3,4,5])
print(np.mean(mat))
print(np.median(mat))
print(np.var(mat))
print(np.std(mat))

In [ ]:
data=np.loadtxt("/content/data analysis using python text file downloaded.txt",dtype=int)
a=np.savetxt("/content/date analysis using python text file.txt",data)
print(data)
print(a)

In [ ]:
import matplotlib.pyplot as plt

In [ ]:
a=np.array([1,2,3,4,5,6,7])
b=np.array([1,0,21,23,34,23])
plt.plot(a)
plt.plot(b)

In [ ]:
import pandas as pd

In [ ]:
a=["Shannu","Abhi","Pradeep","Phani"]
r=pd.Series(a,index=[61,4,30,48])
print(r)

In [ ]:
df=pd.read_csv("/content/combined_data.csv")
print(df)
print(df.loc[1])

In [ ]:
df=pd.read_csv("/content/data text file.txt")
print(df)
print(df.loc[1])


In [ ]:
df=pd.read_csv("/content/DataFile Discrete CSV.data")
mv=df['81'].mean()
print("AVERAGE",mv)
dfn=df.fillna(mv)
print(dfn)
dfn=dfn.drop_duplicates()
print(dfn)

In [ ]:
df=pd.read_excel("/content/Covid Dashboard.xlsx",sheet_name=0)
df.shape
print(df.groupby(['Zone'])['Total Cases'].count())

In [ ]:
df=pd.read_csv("/content/combined_data.csv")
tail=df.tail(10)
#print(tail)
#print(head)
shape=df.shape
print(shape)
#print(tail)
for i in range(83437,83448,-1):
  df.drop([i],axis=0,inplace=True)
total_data=pd.concat([tail],axis=0)
print(total_data)
total_data.to_csv("Last_10_lines3.csv")

In [ ]:
df=pd.read_csv("/content/Last_10_lines.csv")
print(df.groupby(['label'])['text'].count())

label
0    4
1    6
Name: text, dtype: int64


In [ ]:
from google.colab import drive
drive.mount("/content/drive/")

In [ ]:
runs=np.array([100,50,91,78,89,25,34,19,9,10])
w=np.array([1,0,2,0,3,7,8,9,7,5])
plt.plot(runs,w,color='orange')
plt.title("Ind Vs Pak Score")
plt.show()

In [ ]:
#generate array of 200 values b/w -pi and pi
tiger=np.linspace(-2*np.pi,2*np.pi,50)
print(tiger)

plt.scatter(tiger,np.sin(tiger),color="red")
plt.title("Sin(x)")
plt.show()

In [ ]:
#creating x
overs=np.arange(5,50,5)
overs_a=np.arange(5,30,5)
#creating y
runs_i=np.array([35,51,84,131,160,189,220,250,267])
runs_a=np.array([15,41,94,110,151])
wickets=np.array([12,32,96])
#plotting
plt.plot(overs,runs_i,color='blue',label='India')
plt.plot(overs_a,runs_a,color='green',label='pakistan')
#cobining two graphs
plt.legend(loc='best')     #.legend is used to represent the label
plt.show()


In [ ]:
a=[230,560,780,127,128]
b=[200,160,270,127,400]
yrs=[1,2,3,4]

profit_a=[(a[i]-a[i-1]) for i in range(1,len(a))]
profit_b=[(b[i]-b[i-1]) for i in range(1,len(b))]
plt.subplot(2,1,2)
plt.plot(yrs,profit_a,color='hotpink',linewidth='3',label='Company A',marker='*',ms='15',mec='k')
plt.subplot(2,1,1)
plt.plot(yrs,profit_b,color='black',linestyle='dotted',label='Company B',marker='H')

In [ ]:
a=np.array([25,60,5,10])
label=["AIML","Python","Pandas","Numpy"]
colors=['green','blue','black','yellow']
plt.pie(a,labels=label,colors=colors)
plt.show()

In [ ]:
a=np.array([25,60,5,10])
label=["AIML","Python","Pandas","Numpy"]
explo=[0.2,0,0,0]
plt.pie(a,labels=label,explode=explo,startangle=180,textprops={"fontsize":20})
plt.legend(loc='lower right')
plt.show()

In [ ]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd
df=pd.read_excel("/content/drive/MyDrive/DAP_TEAM 7/22A81A0561/temperature analysis.xlsx")
print(df)
avgtemp=df['TEMPERATURE'].mean()
df=df.fillna(avgtemp)
a1=np.array(df['TEMPERATURE'])
maxtemp=df['TEMPERATURE'].max()
mintemp=df['TEMPERATURE'].min()
days=[a1[i] for i in range(1, len(a1)) if a1[i]>avgtemp]
date=np.array(df['DAY'])
plt.plot(date,a1,color='blue',linewidth='2',label='Temperature',marker='*',ms='10',mec='b')
plt.legend(loc='best')
print('Mean =',avgtemp)
print('Maximum =',maxtemp)
print('Minimum =',mintemp)
print('Threshold',avgtemp,'is',len(days),'DAY')
plt.show()

In [ ]:
pip install seaborn

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt


In [ ]:
tips=sns.load_dataset("tips")
sns.scatterplot(x="total_bill",y="tip",data=tips)
plt.title("scatter plot of total bill vs Tip")
plt.xlabel("Total bill ($)")
plt.ylabel("Tip ($)")
plt.show()
tips.head(10)

In [ ]:
import seaborn as sns
anscombe = sns.load_dataset("anscombe")
sns.scatterplot(x="x",y="y",data=anscombe)
plt.show()

In [ ]:
tips=sns.load_dataset("tips")
sns.violinplot(x="day",y="total_bill",data=tips)
plt.title("Distribution of total bill by day")
plt.xlabel("Day of the week")
plt.ylabel("Total bill ($)")
plt.show()

In [ ]:
import seaborn as sns
iris = sns.load_dataset("iris")
correlation_matrix=iris.corr()
sns.heatmap(correlation_matrix,annot=True,cmap="coolwarm")
plt.title("Correlation Heatmap of iris Dataset")
plt.show()
print(iris)

In [ ]:
import seaborn as sns
import matplotlib.pyplot as plt

# Load the titanic dataset
titanic = sns.load_dataset("titanic")

# Create a pairplot
sns.pairplot(titanic)
plt.suptitle("Pairplot of Titanic Dataset", y=1.02)
plt.show()

# Print the titanic dataset
print(titanic)
